Darbuotojai.MVC/Models/ErrorViewModel.cs
using System;

namespace Darbuotojai.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Darbuotojai.MVC/Controllers/DarbuotojasController.cs
using System.Linq;
using System.Threading.Tasks;
using Darbuotojai.Application.Services;
using Darbuotojai.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Darbuotojai.MVC.Controllers
{
    public class DarbuotojasController : Controller
    {
        
        private IDarbuotojaiService _darbuotojaiService;

        public DarbuotojasController(IDarbuotojaiService darbuotojaiService)
        {
            _darbuotojaiService = darbuotojaiService;
        }
        
        
        // GET: Darbuotojas
        public async Task<IActionResult> Index(string filtras)
        {
            
            var model = await _darbuotojaiService.GetDarbuotojai();
            
            ViewData["filtras"] = "visi";
            
            if (!string.IsNullOrEmpty(filtras))
            {
                if (filtras == "aktyvus")
                {
                    model = await _darbuotojaiService.GetFiltered(true);
                    ViewData["filtras"] = "aktyvus";
                }

                if (filtras == "neAktyvus")
                {
                    model = await _darbuotojaiService.GetFiltered(false);
                    ViewData["filtras"] = "neAktyvus";
                }
                
                
            }
            
            
            
            return View(model);
        }

        // GET: Darbuotojas/Details/5
        public async Task<IActionResult> Details(int id)
        {

            var darbuotojas = await _darbuotojaiService.GetDetails(id);
            
            if (darbuotojas == null)
            {
                return NotFound();
            }

            return View(darbuotojas);
        }

        // GET: Darbuotojas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Darbuotojas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Vardas,Pavardė,AsmensKodas,GimimoData,NamoNumeris,Gatve,Miestas,PastoKodas,Aktyvus")] DarbuotojasDto darbuotojas)
        {
            if (ModelState.IsValid)
            {
               await _darbuotojaiService.Create(darbuotojas.Vardas,  darbuotojas.Pavardė,  darbuotojas.AsmensKodas,  darbuotojas.GimimoData, darbuotojas.NamoNumeris,
                    darbuotojas.Gatve,  darbuotojas.Miestas,  darbuotojas.PastoKodas, darbuotojas.Aktyvus);
               
                return RedirectToAction(nameof(Index));
            }
            return View(darbuotojas);
        }

        // GET: Darbuotojas/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var darbuotojas = await _darbuotojaiService.GetDetails(id);
            if (darbuotojas == null)
            {
                return NotFound();
            }
            return View(darbuotojas);
        }

        // POST: Darbuotojas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Vardas,Pavardė,AsmensKodas,GimimoData,NamoNumeris,Gatve,Miestas,PastoKodas,Aktyvus")] DarbuotojasDto darbuotojas)
        {
            if (id != darbuotojas.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                  await  _darbuotojaiService.Update(darbuotojas.Id, darbuotojas.Vardas,  darbuotojas.Pavardė,  darbuotojas.AsmensKodas,  darbuotojas.GimimoData, darbuotojas.NamoNumeris,
                        darbuotojas.Gatve,  darbuotojas.Miestas,  darbuotojas.PastoKodas, darbuotojas.Aktyvus);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var darbuotojasExists = await DarbuotojasExists(darbuotojas.Id);
                    
                    if (!darbuotojasExists)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(darbuotojas);
        }

        // GET: Darbuotojas/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var darbuotojas = await _darbuotojaiService.GetDetails(id);
            if (darbuotojas == null)
            {
                return NotFound();
            }
            return View(darbuotojas);
        }

        // POST: Darbuotojas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _darbuotojaiService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> DarbuotojasExists(int id)
        {

            var darbuotojai = await _darbuotojaiService.GetDarbuotojai();
            
            return darbuotojai.Any();
        }
    }
}

Darbuotojai.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Darbuotojai.MVC.Models;

namespace Darbuotojai.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Darbuotojai.MVC/Views/Darbuotojas/Create.cshtml
@model Darbuotojai.Application.ViewModels.DarbuotojasDto
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Darbuotojas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Vardas" class="control-label"></label>
                <input asp-for="Vardas" class="form-control" />
                <span asp-validation-for="Vardas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pavardė" class="control-label"></label>
                <input asp-for="Pavardė" class="form-control" />
                <span asp-validation-for="Pavardė" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AsmensKodas" class="control-label"></label>
                <input asp-for="AsmensKodas" class="form-control" />
                <span asp-validation-for="AsmensKodas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GimimoData" class="control-label"></label>
                <input asp-for="GimimoData" type="date" class="form-control" />
                <span asp-validation-for="GimimoData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamoNumeris" class="control-label"></label>
                <input asp-for="NamoNumeris" class="form-control" />
                <span asp-validation-for="NamoNumeris" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gatve" class="control-label"></label>
                <input asp-for="Gatve" class="form-control" />
                <span asp-validation-for="Gatve" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Miestas" class="control-label"></label>
                <input asp-for="Miestas" class="form-control" />
                <span asp-validation-for="Miestas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PastoKodas" class="control-label"></label>
                <input asp-for="PastoKodas" class="form-control" />
                <span asp-validation-for="PastoKodas" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aktyvus" /> @Html.DisplayNameFor(model => model.Aktyvus)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Darbuotojai.MVC/Views/Darbuotojas/Delete.cshtml
@model Darbuotojai.Application.ViewModels.DarbuotojasDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Darbuotojas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vardas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vardas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pavardė)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pavardė)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AsmensKodas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AsmensKodas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GimimoData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GimimoData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamoNumeris)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamoNumeris)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gatve)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gatve)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Miestas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Miestas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PastoKodas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PastoKodas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aktyvus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aktyvus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Darbuotojai.MVC/Views/Darbuotojas/Details.cshtml
@model Darbuotojai.Application.ViewModels.DarbuotojasDto
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Darbuotojas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vardas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vardas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pavardė)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pavardė)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AsmensKodas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AsmensKodas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GimimoData)
        </dt>
        <dd class="col-sm-10">
            @Model.GimimoData.ToString("yyyy-mm-dd")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamoNumeris)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamoNumeris)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gatve)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gatve)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Miestas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Miestas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PastoKodas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PastoKodas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aktyvus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aktyvus)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Darbuotojai.MVC/Views/Darbuotojas/Edit.cshtml
@model Darbuotojai.Application.ViewModels.DarbuotojasDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Darbuotojas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Vardas" class="control-label"></label>
                <input asp-for="Vardas" class="form-control" />
                <span asp-validation-for="Vardas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pavardė" class="control-label"></label>
                <input asp-for="Pavardė" class="form-control" />
                <span asp-validation-for="Pavardė" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AsmensKodas" class="control-label"></label>
                <input asp-for="AsmensKodas" class="form-control" />
                <span asp-validation-for="AsmensKodas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GimimoData" class="control-label"></label>
                <input asp-for="GimimoData" type="date" class="form-control" />
                <span asp-validation-for="GimimoData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamoNumeris" class="control-label"></label>
                <input asp-for="NamoNumeris" class="form-control" />
                <span asp-validation-for="NamoNumeris" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gatve" class="control-label"></label>
                <input asp-for="Gatve" class="form-control" />
                <span asp-validation-for="Gatve" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Miestas" class="control-label"></label>
                <input asp-for="Miestas" class="form-control" />
                <span asp-validation-for="Miestas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PastoKodas" class="control-label"></label>
                <input asp-for="PastoKodas" class="form-control" />
                <span asp-validation-for="PastoKodas" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aktyvus" /> @Html.DisplayNameFor(model => model.Aktyvus)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Darbuotojai.MVC/Views/Darbuotojas/Index.cshtml
@model IEnumerable<Darbuotojai.Application.ViewModels.DarbuotojasDto>
@{
    ViewData["Title"] = "Darbuotojai CRUD";
}

<h1>Darbuotojai</h1>

@using (Html.BeginForm())
{
    <div class="row">
            <div class="col-6 col-sm-3">

                @if ((string) ViewData["filtras"] == "visi")
                {
                    <label class="radio-inline">
                        <input value="visi" id="visi" type="radio" name="filtras" checked onchange="this.form.submit()"> Visi Darbuotojai
                    </label>
                }
                else
                {
                    <label class="radio-inline">
                        <input value="visi" id="visi" type="radio" name="filtras" onchange="this.form.submit()"> Visi Darbuotojai
                    </label>
                }
            </div>
            <div class="w-100"></div>

            <div class="col-6 col-sm-3">

                @if ((string) ViewData["filtras"] == "aktyvus")
                {
                    <label class="radio-inline">
                        <label class="radio-inline"><input value="aktyvus" id="aktyvus" type="radio" name="filtras" checked onchange="this.form.submit()"> Aktyvūs</label>
                    </label>
                }
                else
                {
                    <label class="radio-inline">
                        <label class="radio-inline"><input value="aktyvus" id="aktyvus" type="radio" name="filtras" onchange="this.form.submit()"> Aktyvūs</label>
                    </label>
                }

            </div>

            <div class="w-100"></div>

            <div class="col-6 col-sm-3">
                @if ((string) ViewData["filtras"] == "neAktyvus")
                {
                    <label class="radio-inline"><input value="neAktyvus" id="neAktyvus" type="radio" name="filtras" checked onchange="this.form.submit()"> Neaktyvūs</label>
                }
                else
                {
                    <label class="radio-inline"><input value="neAktyvus" id="neAktyvus" type="radio" name="filtras" onchange="this.form.submit()"> Neaktyvūs</label>
                }
            </div>
        </div>
}
<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Vardas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pavardė)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AsmensKodas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GimimoData.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NamoNumeris)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gatve)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Miestas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PastoKodas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aktyvus)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Vardas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pavardė)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AsmensKodas)
            </td>
            <td>
                @item.GimimoData.ToString("yyyy-mm-dd")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NamoNumeris)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gatve)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Miestas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PastoKodas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aktyvus)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
    }
    </tbody>
</table>

Darbuotojai.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Sveiki!</h1>
    <p>Darbuotojų CRUD atsidarys paspaudus "Santa Testas".</p>
</div>

Darbuotojai.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Darbuotojai.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Darbuotojas" asp-action="Index">Santa Testas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Darbuotojai.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>